### PR TITLE
Add filibustering to CoC

### LINKED ISSUE #26: Code of Conduct
Should we add one?

### PR DESCRIPTION
**Pull request by sambattalio**

### CODE REVIEW

**Comment by AndroidKitKat** [comment]
I like this idea, in the event of standstill, I nominate @pbui to be the tie breaker

**Review by AndroidKitKat — APPROVED** [review]
YEAH I LIKE IT

**Comment by wtheisen** [comment]
Great idea guys

**Review by ghost — APPROVED** [review]
Looks good!

**Pull request merged**
