### PR TITLE
Change to MIT

### LINKED ISSUE #77: Change to MIT License
Just saw this comment on Reddit: https://www.reddit.com/r/Zig/comments/g1umkx/small_linux_userland_built_in_zig/fnhqfac/

I want the project to be open for anyone to use without worrying of our license. 

Thoughts?

### PR DESCRIPTION
**Pull request by AndroidKitKat**
closes #77

### CODE REVIEW

**Comment by sambattalio** [comment]
LMAO this broke my test

**Comment by sambattalio** [comment]
https://github.com/pbui-project/pbui-main/blob/1eafe64ef4f544cdc4c97c97b6dcc254792df6e2/src/du.zig#L166

Would you mind changing this value to be the actual disk usage of the new `LICENCE` value?

**Comment by AndroidKitKat** [comment]
I think this should do it

**Comment by sambattalio** [comment]
let me see, im not sure if it "did" it. I kinda magic numbered it a little (my bad didn't think it was gonna need to be touched again)

**Comment by sambattalio** [comment]
OH oops now the sha1 test is failing too 😓 here i can fix that rq

**Pull request merged**
