### PR TITLE
ls code cleanups to enable long mode

### PR DESCRIPTION
**Pull request by sig1nt**
I also updated every test in the repo with regards to ls to meet the new behavior

### CODE REVIEW

**Comment by sambattalio** [comment]
This LGTM, however it looks like it doesn't print the tabs anymore. Was this intended? I didn't make this applet so it might be better if @jcharbon-nd took a look at it also. Thanks for the PR btw :D

**Comment by jcharbon-nd** [comment]
If removing the tabs was accidental, it look like all we have to do to re implement them is to put
`printTabs(TABS)` above the print statement in the show_file function. 

This cleanup of some of the code is much appreciated atti1a :) I have been primarily focused on making ls work in general thus far, so it's quite clunky. I'm totally in favor of any further changes in order to make it even more clean. 

I'll merge this request and add the tabs for recursion back in, but if you intended to remove them just let me know and we can discuss further. I can see where the tabs might get in the way of a long mode looking good so I could see there might be intent there so just lmk

**Review by jcharbon-nd — COMMENTED** [review]
See comment in PR thread

**Comment by sig1nt** [comment]
Ah, so this is the result of me being a clown. The original PR had the `printTabs` function put into `show_file`, but I tried to be fancy with a `git add -p .`

I'll be more careful in the future

**Pull request merged**
