### PR TITLE
symlinkable and generalized basename

### PR DESCRIPTION
**Pull request by sambattalio**
Made base name more general to return a []u8.

Also made it so you can symlink ./zigcache/..../pbui to ./APPLET_NAME!

Got rid of arg parsing in main to facilitate this and hard coded in -h checks.

### CODE REVIEW

**Comment by ginglis13** [comment]
:rocket: really looking forward to seeing these changes in action!

**Comment by AndroidKitKat** [comment]
Hmmm, this seems to fail CI. I cannot in good faith merge this PR.

**Comment by sambattalio** [comment]
I think the Linter is broken because its ahead of our zig version

**Comment by AndroidKitKat** [comment]
Sounds like a great opportunity for a community PR!

**Comment by sambattalio** [comment]
no u

**Comment by AndroidKitKat** [comment]
yeah it looks good

**Comment by sambattalio** [comment]
thanks bruv ill look into updating zig

**Pull request merged**
